# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redocly.com/docs/cli/ for more information.
specs/openapi.yaml:
  no-empty-servers:
    - '#/openapi'
  operation-4xx-response:
    - '#/paths/~1health/get/responses'
