services:
    backend:
      image: ghcr.io/kwila-cloud/simple-sync:latest
      ports:
        - "8080:8080"
      volumes:
        - data:./data
      environment:
        - JWT_SECRET=${JWT_SECRET}
      restart: unless-stopped
