services:
  simple-sync:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=${JWT_SECRET:-your-development-secret-key-change-this-in-production}
      - PORT=8080
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "-s", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - simple-sync-network

networks:
  simple-sync-network:
    driver: bridge

volumes:
  simple-sync-data:
    driver: local