openapi: 3.0.3
info:
  title: Exchange Token API
  description: Exchange setup tokens for API keys
  version: 1.0.0

paths:
  /api/v1/setup/exchangeToken:
    post:
      summary: Exchange setup token for API key
      description: Exchange a valid setup token for a long-lived API key. The setup token itself provides authentication for this operation.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  pattern: '^[A-Z0-9]{4}-[A-Z0-9]{4}$'
                  description: Setup token to exchange
                description:
                  type: string
                  maxLength: 100
                  description: Optional description for the API key (e.g., "Mobile App", "Desktop Client")
              required:
                - token
      responses:
        '200':
          description: Token exchanged successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  keyUuid:
                    type: string
                    format: uuid
                    description: Unique identifier for the API key
                  apiKey:
                    type: string
                    pattern: '^sk_[A-Za-z0-9+/]{43}$'
                    description: API key with sk_ prefix
                  user:
                    type: string
                    description: User ID
                  description:
                    type: string
                    description: API key description (if provided)
                required:
                  - keyUuid
                  - apiKey
                  - userId
        '400':
          description: Invalid request or token format
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid token format"
                required:
                  - error
        '401':
          description: Authentication failed, token expired/used, or insufficient permissions
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Unauthorized"
                required:
                  - error
        '401':
          description: Authentication failed, token expired/used, or insufficient permissions
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Unauthorized"
                required:
                  - error
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal server error"
                required:
                  - error

components: {}</content>
</xai:function_call">**Output**: exchange-token-api.yaml contract specification