openapi: 3.0.3
info:
  title: Simple-Sync Health Check API
  version: 1.0.0
  description: Health check endpoint for container orchestration

paths:
  /health:
    get:
      summary: Health check endpoint
      description: Returns service health status for container orchestration
      operationId: getHealth
      tags:
        - Health
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
              example:
                status: "healthy"
                timestamp: "2025-09-20T10:30:00Z"
                version: "v0.1.0"
                uptime: 3600
        '503':
          description: Service is unhealthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
              example:
                status: "unhealthy"
                timestamp: "2025-09-20T10:30:00Z"
                version: "v0.1.0"
                uptime: 3600

components:
  schemas:
    HealthResponse:
      type: object
      required:
        - status
        - timestamp
        - version
        - uptime
      properties:
        status:
          type: string
          enum: [healthy, unhealthy]
          description: Current health status
          example: "healthy"
        timestamp:
          type: string
          format: date-time
          description: ISO 8601 timestamp of health check
          example: "2025-09-20T10:30:00Z"
        version:
          type: string
          description: Application version
          example: "v0.1.0"
        uptime:
          type: integer
          minimum: 0
          description: Service uptime in seconds
          example: 3600