openapi: 3.0.0
info:
  title: Simple-Sync API
  version: 1.0.0
servers:
  - url: http://localhost:8080/v1
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
  /events:
    post:
      summary: Create event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '201':
          description: Created
    get:
      summary: List events
      responses:
        '200':
          description: OK
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
security:
  - ApiKeyAuth: []
