openapi: 3.0.3
info:
  title: simple-sync ACL API
  version: 1.0.0
  description: API for managing access control lists

paths:
  /acl:
    get:
      summary: Retrieve ACL entries
      responses:
        '200':
          description: List of ACL entries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ACLEntry'
    put:
      summary: Update ACL entries
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/ACLEntry'
      responses:
        '204':
          description: ACL updated successfully

components:
  schemas:
    ACLEntry:
      type: object
      required:
        - userUuid
        - itemUuid
        - permissions
      properties:
        userUuid:
          type: string
        itemUuid:
          type: string
        permissions:
          type: array
          items:
            type: string
            enum: [read, write]