openapi: 3.0.3
info:
  title: simple-sync Authentication API
  version: 1.0.0
  description: API for user authentication

paths:
  /auth/token:
    post:
      summary: Generate authentication token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Authentication token
          content:
            application/json:
              schema:
                type: object
                required:
                  - token
                properties:
                  token:
                    type: string

components:
  schemas:
    AuthRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
    AuthResponse:
      type: object
      required:
        - token
      properties:
        token:
          type: string