openapi: 3.0.3
info:
  title: simple-sync Events API
  version: 1.0.0
  description: API for managing timestamped events

paths:
  /events:
    get:
      summary: Retrieve events
      parameters:
        - name: fromTimestamp
          in: query
          schema:
            type: integer
            format: int64
          description: Filter events from this timestamp
      responses:
        '200':
          description: List of events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
    post:
      summary: Post new events
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Event'
      responses:
        '200':
          description: Updated complete event history
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'

components:
  schemas:
    Event:
      type: object
      required:
        - uuid
        - timestamp
        - userUuid
        - itemUuid
        - action
        - payload
      properties:
        uuid:
          type: string
          format: uuid
        timestamp:
          type: integer
          format: int64
        userUuid:
          type: string
          format: uuid
        itemUuid:
          type: string
          format: uuid
        action:
          type: string
          enum: [create, update, delete]
        payload:
          type: string