// Code generated by GitHub workflow. DO NOT EDIT.
// This file is auto-generated when releasing a new version.
// Manual changes will be overwritten.

package main

// Version is the current version of the application
var Version = "0.0.0"

// BuildTime is set at build time
var BuildTime = "Unknown"
