openapi: 3.0.3
info:
  title: Simple-Sync API Authentication
  description: API key authentication using X-API-Key header
  version: 1.0.0

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: API key for authentication

  responses:
    Unauthorized:
      description: Authentication failed
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Invalid API key"
    BadRequest:
      description: Invalid request
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "X-API-Key header required"

security:
  - ApiKeyAuth: []

paths:
  /api/v1/events:
    get:
      summary: Get events
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: Success
        '401':
          $ref: '#/components/responses/Unauthorized'
    post:
      summary: Create events
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: Success
        '401':
          $ref: '#/components/responses/Unauthorized'

  /api/v1/health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK

  /api/v1/user/generateToken:
    post:
      summary: Generate setup token
      responses:
        '200':
          description: Success

  /api/v1/setup/exchangeToken:
    post:
      summary: Exchange setup token for API key
      responses:
        '200':
          description: Success