name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  validate-openapi:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Run OpenAPI lint
      run: bash tests/contract/validate_openapi.sh

  verify-openapi:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true

    - name: Verify OpenAPI spec
      run: bash tests/contract/verify_openapi.sh

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Download dependencies
      run: go mod download

    - name: Ensure system sqlite3 dependencies (for mattn/go-sqlite3)
      run: sudo apt-get update && sudo apt-get install -y build-essential libsqlite3-dev

    - name: Check code formatting
      run: |
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
          echo "The following files are not formatted:"
          gofmt -s -l .
          exit 1
        fi

    - name: Run go vet
      run: go vet ./...

    - name: Run unit, contract, and integration tests
      run: go test -race ./tests/unit ./tests/contract ./tests/integration

    - name: Run performance tests
      run: go test ./tests/performance

